default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  - pre-push
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.3
    hooks:
      - id: uv-sync
        args: ["--locked", "--all-packages"]
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Turn this off for now, as its not configured correctly
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0  # Use the sha / tag you want to point at
  #   hooks:
  #   -   id: mypy
  #       args: ["--strict", "--ignore-missing-imports"]
  #       additional_dependencies: ["numpy.typing", "pandas-stubs", "typeshed-client"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
