name: Bump version

on:
  pull_request

  # push:
  #   branches:
  #     - main

jobs:
  bump-version:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: "Bump version, create changelog, and tag github release"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: body.md
          dry_run: true

      # - name: Github release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     body_path: "body.md"
      #     tag_name: ${{ env.REVISION }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
