name: tests
run-name: ${{ github.actor }} is testing out DOVE
on: [push, pull_request]
jobs:
  test-dove-linux:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # - name: Lint with Ruff
      #   run: |
      #     # Run Ruff for linting
      #     uvx ruff check .  

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest --cov src/dove

