name: GitHub DOVE test
run-name: ${{ github.actor }} is testing out DOVE
on: [push, pull_request]
jobs:
  Test-DOVE-Linux:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: cd .. && rm -Rf raven && git clone https://github.com/idaholab/raven.git
      - run: python3 ../raven/scripts/install_plugins.py -s ${{ github.workspace }}
      - run: >
          WD=`(cd ../../.. && pwd)` && export RAVEN_LIBS_NAME="raven_libs_"`basename $WD` &&
          CONDA_LOC=`which conda` && CDEFS_LOC=`cd $CONDA_LOC/../.. && pwd`"/etc/profile.d/conda.sh" &&
          ../raven/scripts/establish_conda_env.sh --install --conda-defs=$CDEFS_LOC
      - run: cd ../raven && ./build_raven
      - run: ../raven/run_tests --library-report
      - run: bash coverage_scripts/check_py_coverage.sh -j4
      # report_py_coverage is being called twice, once within check_py_coverage to print to the terminal and once here to get data for the annotation
      - run: >
          DATA_FILE=`pwd`/.coverage && COV_RCFILE=`pwd`/coverage_scripts/.coveragerc &&
          COV_RPT=`bash coverage_scripts/report_py_coverage.sh --data-file=$DATA_FILE --coverage-rc-file=$COV_RCFILE` &&
          echo "::notice title=Coverage Summary::$COV_RPT For details, download 'coverage_results' from Artifacts, extract all files, and open 'index.html'."
      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage_results
          path: tests/coverage_html_report
  Test-DOVE-Windows:
    runs-on: [windows-latest]
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: cd ..; if (Test-Path raven) {Remove-Item -Recurse -Force raven}; git clone https://github.com/idaholab/raven.git
      - run: python ../raven/scripts/install_plugins.py -s ${{ github.workspace }}
      - run: >
          $Env:RAVEN_LIBS_NAME =  "raven_libraries_"+(Get-Location).Path.Split("\")[-4];
          CONDA_LOC=`which conda`; CDEFS_LOC=`cd $CONDA_LOC/../.. && pwd`"/etc/profile.d/conda.sh";
          bash ../raven/scripts/establish_conda_env.sh --install --conda-defs $CDEFS_LOC
      - run: cd ../raven; bash ./build_raven
      - run: bash ../raven/run_tests --library-report
      - run: bash ../raven/run_tests -j4 --re=DOVE/tests
