name: GitHub DOVE test
run-name: ${{ github.actor }} is testing out DOVE
on: [push, pull_request]
jobs:
  Test-DOVE-Linux:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with Ruff
        run: |
          # Run Ruff for linting
          uvx ruff check .  

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest --cov src/dove

